### ISSUE TITLE
Can we expose the function that generates code without writing a file?

### ISSUE THREAD

**Issue by gtarsia** [cwqt/refract#17]
I think it'd be nice if the codegen function was exposed, because maybe people don't want to write a file. I imagine this would be exposing the default exported function at `codegen.ts` as a `codegen` named export from `index.ts` 

I could do a merge request myself.

Also, it'd be nice to have some other things, like making some arguments optional, or being able to generate a "Refract" instance from a prisma schema, or even merge between two "Refract" instances. I could help out with these things, if you want we could chat on discord/slack about these things.

**Comment by cwqt** [comment]
> I think it'd be nice if the codegen function was exposed, because maybe people don't want to write a file. I imagine this would be exposing the default exported function at codegen.ts as a codegen named export from index.ts

sorry for the long delay - I've exported the `codegen` function into `Refract.generate` in release `1.3.10`, as for the other feature requests I don't have capacity at the moment to invest time into them

> or being able to generate a "Refract" instance from a prisma schema

Would be difficult since you'd need to traverse the Prisma AST and map into Refract/TS, would say that's outside the scope of what this library should do.

> or even merge between two "Refract" instances.

You should already be able to do that by `cat`ing the output of the two generated Prisma files together, or by merging the `schema` array pre-generation.
